---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visheshcapstone
  namespace: default
  labels:
    app: visheshcapstone
spec:
  replicas: 4
  selector:
    matchLabels:
      app: visheshcapstone
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: visheshcapstone
    spec:
      containers:
        - name: visheshcapstone
          image: visheshvashista/visheshcapstone
          imagePullPolicy: Always
          name: visheshcapstone
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: "visheshcapstone-lb"
spec:
  type: LoadBalancer
  selector:
    app: visheshcapstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
