apiVersion: apps/v1
kind: Deployment
metadata:
  name: visheshCapstone
  labels:
    app: visheshCapstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: visheshCapstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: visheshCapstone
    spec:
      containers:
        - image: visheshvashista/visheshCapstone
          imagePullPolicy: Always
          name: visheshCapstone
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: visheshCapstone
  labels:
    app: visheshCapstone
spec:
  type: LoadBalancer
  selector:
    app: visheshCapstone
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
