---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visheshcapstone
  labels:
    app: visheshcapstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: visheshcapstone
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  minReadySeconds: 60
  progressDeadlineSeconds: 1800
  template:
    metadata:
      labels:
        app: visheshcapstone
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: visheshcapstone
          image: visheshvashista/visheshcapstone
          imagePullPolicy: Always
          name: visheshcapstone
          ports:
            - containerPort: 80
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              scheme: HTTP
              port: 8888
            successThreshold: 1
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: "visheshcapstone-lb"
spec:
  type: LoadBalancer
  selector:
    app: visheshcapstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
