# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
orbs:
  aws-eks: circleci/aws-eks@1.0.3
  kubernetes: circleci/kubernetes@0.11.2

jobs:
  build:
    docker:
      - image: circleci/python:3.7.8-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      
      - setup_remote_docker:
          version: 19.03.13        
            
      - run:
          name: install project dependencies
          command: |
            sudo apt-get update
            sudo apt-get install python3-venv
            python3 -m venv venv
            . venv/bin/activate
            make install
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            sudo chmod +x /bin/hadolint
    
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint 
               
      - run:
          name: create docker image
          command: |
            chmod 777 run_docker.sh make_prediction.sh upload_docker.sh
            ./run_docker.sh
            docker ps -a
            
      - run:
          name: publish docker image
          command: |
            echo $DockerPassword | docker login --username visheshvashista --password-stdin
            ./upload_docker.sh
       
      - run:
          name: create eks cluster 
          command: |
            python3 -m venv venv
            . venv/bin/activate
            isclustercreated=`aws eks  list-clusters --output text | grep -c visheshCapstone`
            if [ $isclustercreated -eq 1 ]
            then
               echo "cluster already exists"
            else
              eksctl create cluster --name visheshCapstone --version 1.17 --nodegroup-name nworkercap --node-type t2.micro --nodes 2 --nodes-min 1 --nodes-max 3 --node-ami auto --region us-west-2
            fi
         
      - run:
          name: deploy to eks cluster 
          command: |
            stackarn=`aws cloudformation describe-stacks --stack-name "eksctl-visheshCapstone-cluster" --query "Stacks[*].StackId" --output text`
            aws eks --region us-west-2 update-kubeconfig --name visheshCapstone
            kubectl config use-context $stackarn:cluster/visheshCapstone
            kubectl set image deployments/visheshCapstone udacapstone=visheshvashista/visheshCapstone:latest
            kubectl apply -f deployment.yml
            kubectl get nodes
            kubectl get deployment
            kubectl get pod -o wide
            kubectl get service/visheshCapstone
       
workflows:
  default:
    jobs:
      - build