# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install awscli
            
      - run:
          name: Install docker
          command: |
            sudo apt-get update
            sudo apt-get install docker
      
      - run:
          name: Install kubectl
          command: |
            sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2 curl
            curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
            sudo apt-get update
            sudo apt-get install -y kubectl

      - run: 
          name: Install eksctl
          command: |    
            sudo apt-get update
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin
            eksctl version           
            
      - run:
          name: install project dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ./venv
            
  runlint:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout 
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-      
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint 
    
  createcluster:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - run:
          name: create eks cluster 
          command: |
            python3 -m venv venv
            . venv/bin/activate
            isclustercreate=`aws eks  list-clusters --output text | grep -c visheshCapstone`
            if [ isclustercreate -eq 1 ]
            then
               echo "cluster already exists"
            else
              eksctl create cluster --name visheshCapstone --version 1.17 --nodegroup-name nworkercap --node-type t2.micro --nodes 2 --nodes-min 1 --nodes-max 3 --node-ami auto --region us-west-2
            fi
 
  deploytocluster:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:            
      - run:
          name: deploy to eks cluster 
          command: |
            stackarn=`aws cloudformation describe-stacks --stack-name "eksctl-visheshCapstone-cluster" --query "Stacks[*].StackId" --output text`
            aws eks --region us-west-2 update-kubeconfig --name visheshCapstone
            kubectl config use-context $stackarn:cluster/visheshCapstone
            kubectl set image deployments/visheshCapstone udacapstone=visheshvashista/visheshCapstone:latest
            kubectl apply -f deployment.yml
            kubectl get nodes
            kubectl get deployment
            kubectl get pod -o wide
            kubectl get service/visheshCapstone
       
workflows:
  default:
    jobs:
      - build
