# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.7-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install awscli
                 
      - run:
          name: Install systemd
          command: |
            
            sudo apt-get update
            docker images

      - run:
          name: Install kubectl
          command: |
            sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2 curl
            curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
            sudo apt-get update
            sudo apt-get install -y kubectl

      - run: 
          name: Install eksctl
          command: |    
            sudo apt-get update
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin
            eksctl version           
            
      - run:
          name: install project dependencies
          command: |
            sudo apt-get update
            sudo apt-get install python3-venv
            python3 -m venv venv
            . venv/bin/activate
            make install
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            sudo chmod +x /bin/hadolint
    
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint 
            
      - run:
          name: check docker is running or not
          command: |
            docker images
    
      - run:
          name: start docker
          command: |
            sudo systemctl start docker
            
      - run:
          name: create docker image
          command: |
            ./run_docker.sh
            ./make_predictions.sh
            
      - run:
          name: publish docker image
          command: |
            ./upload_docker.sh
 
       
workflows:
  default:
    jobs:
      - build
