# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
orbs:
  aws-eks: circleci/aws-eks@1.0.3
  kubernetes: circleci/kubernetes@0.11.2

jobs:
  build:
    docker:
      - image: circleci/python:3.7.8-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install project dependencies
          command: |
            sudo apt-get update
            sudo apt-get install python3-venv
            python3 -m venv venv
            . venv/bin/activate
            make install
            ls -lrt ./venv

      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ./venv

  test-app:
    docker:
    - image: circleci/python:3.7.8-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: run lint
          command: |
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            sudo chmod +x /bin/hadolint
            . venv/bin/activate
            make lint 
               
  build-dockerimage:
    docker:
    - image: circleci/python:3.7.8-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - setup_remote_docker:
          version: 19.03.13  

      - run:
          name: create docker image
          command: |
            . venv/bin/activate
            chmod 777 run_docker.sh make_prediction.sh upload_docker.sh
            ./run_docker.sh
            docker ps -a
            
      - run:
          name: publish docker image
          command: |
            echo $DockerPassword | docker login --username visheshvashista --password-stdin
            ./upload_docker.sh 
  create-cluster: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yum install -y tar gzip 
      - run:
          name: create visehshcapstone cluster if it doesn't exists
          command: |
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            mv /tmp/eksctl /usr/local/bin
            export AWS_PAGER=""
            export eksclusterlist=$(aws eks  list-clusters --output text)
            eksclusterlist=`echo $eksclusterlist | sed '/^$/d' | grep -w visheshcapstone || true`
            isClusterPresent=`echo $eksclisterlist |  grep -c visheshcapstone || true`
            if [ $isClusterPresent == 1 ]
            then
               echo "cluster already exists"
            else
               echo "cluster does not exists.. creating cluster.. please wait"
              eksctl create cluster --name visheshcapstone --version 1.17 --nodegroup-name nworkercap --node-type t2.micro --nodes 2 --nodes-min 1 --nodes-max 2 --node-ami auto --region us-west-2
            fi

  deployapp-to-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          set up cluster
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment.yml
          resource-name: deployment/visheshcapstone
      - run:
          name: update image
          command: |
            kubectl set image deployment/visheshcapstone visheshcapstone=visheshvashista/visheshcapstone
      - kubernetes/get-rollout-status:
          resource-name: deployment/visheshcapstone
          watch-rollout-status: true

  test-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          cluster name
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          command: |
            kubectl get services
            kubectl get nodes
            kubectl get deployment
            kubectl get pod -o wide
            kubectl get service/visheshcapstone
          name: Test cluster
       
workflows:
  default:
    jobs:
      - build
      - test-app:
          requires: [build]
      - build-dockerimage:
           requires: [test-app]
      - deployapp-to-cluster:
          cluster-name: visheshcapstone
          requires: [build-dockerimage]
      - test-cluster:
          cluster-name: visheshcapstone
          requires: [deployapp-to-cluster]
      - aws-eks/delete-cluster:
          cluster-name: visheshcapstone
          requires:
            - test-cluster
